const INCREASE_AMOUNT = "INCREASE_AMOUNT";
const DECREASE_AMOUNT = "DECREASE_AMOUNT";
const SET_CART = "SET_CART";
const CLEAR_CART = "CLEAR_CART";
const REMOVE_ITEM = "REMOVE_ITEM";
const GET_TOTALS = "GET_TOTALS";
const TOGGLE_AMOUNT = "TOGGLE_AMOUNT";
const ADD_TO_CART = "ADD_TO_CART";
const APPLY_COUPON = "APPLY_COUPON";
const APPLY_POINTS = "APPLY_POINTS";

const SET_IS_CART_UPDATING = "SET_IS_CART_UPDATING";
const SET_CART_KEY = "SET_CART_KEY";

export {
  INCREASE_AMOUNT,
  DECREASE_AMOUNT,
  CLEAR_CART,
  REMOVE_ITEM,
  TOGGLE_AMOUNT,
  GET_TOTALS,
  ADD_TO_CART,
  APPLY_COUPON,
  APPLY_POINTS,
  SET_IS_CART_UPDATING,
  SET_CART,
  SET_CART_KEY
};
